### ISSUE TITLE
Groundplex when deployed in k8s as pod doesn't assume the role assigned to it instead but assumes the NODE role

### ISSUE THREAD

**Issue by shaksing** [SnapLogic/developer.snaplogic.com#39]
Groundplex when deployed in AWS EKS(kubernetes) as pod doesn't assume the AWS role assigned to it with the help of service account instead but assumes the NODE role.
I have used the snaplogic/snaplex latest docker image in the helm chart. ( Image Tag : snaplogic/snaplex:main-21624 )

Please fix this issue and let me know if you need any other information.

Thanks
Shakti

**Comment by ddellsperger** [comment]
Please reach out to customer support
